### ISSUE TITLE
Plug-in not working

### ISSUE THREAD

**Issue by arturoovf** [davidmerrique/homebridge-adguardhome#11]
Homebridge v1.3.4
homebridge-adguardhome v1.4.1
Docker image: 
https://hub.docker.com/r/adguard/adguardhome/
Version: 
v0.106.3

config:
```
{
    "host": "192.168.52.7",
    "https": false,
    "port": 3000,
    "username": "admin",
    "password": "admin",
    "name": "AdGuard Home",
    "accessory": "AdGuardHome",
    "_bridge": {
        "username": "0E:47:AD:C7:81:EE",
        "port": 52330
    }
}
```

```
Logs:
[10/4/2021, 4:30:58 PM] [AdGuard Home] RequestError: connect EHOSTUNREACH 192.168.52.7:3000
    at ClientRequest.<anonymous> (/homebridge/node_modules/homebridge-adguardhome/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.origin.emit (/homebridge/node_modules/homebridge-adguardhome/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
  code: 'EHOSTUNREACH',
  timings: {
    start: 1633383055157,
    socket: 1633383055160,
    lookup: undefined,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1633383058270,
    abort: undefined,
    phases: {
      wait: 3,
      dns: undefined,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 3113
    }
  }
}
```

**Comment by arturoovf** [comment]
Version 1.5.0 still same error

**Comment by dwaan** [comment]
Closing this issue due to no responses. But to add to the discussion, this issue can be caused by many problem:
- Can be caused by firewall blocking the access to the ip and or port.
- Can be caused by misconfiguration in the router.
- Can be caused by network isolation issue for example when using docker instances.
- etc.
