### ISSUE TITLE
Home Bridge Connection Fails

### ISSUE THREAD

**Issue by imajhere** [davidmerrique/homebridge-adguardhome#16]
Hi, 

I'm trying to add this plugin to Homebridge for the first time.
Homebridge is running on Windows, and Adguard running on Docker on the same machine.
I get the below error when I try to add the plugin:

5/24/2022, 6:48:51 PM] [homebridge-adguardhome] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[5/24/2022, 6:48:51 PM] [AdGuard] RequestError: socket hang up
    at ClientRequest.<anonymous> (C:\Users\aashi\AppData\Roaming\npm\node_modules\homebridge-adguardhome\node_modules\got\dist\source\core\index.js:962:111)
    at Object.onceWrapper (node:events:642:26)
    at ClientRequest.emit (node:events:539:35)
    at ClientRequest.origin.emit (C:\Users\aashi\AppData\Roaming\npm\node_modules\homebridge-adguardhome\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
    at Socket.socketOnEnd (node:_http_client:478:9)
    at Socket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at connResetException (node:internal/errors:692:14)
    at Socket.socketOnEnd (node:_http_client:478:23)
    at Socket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ECONNRESET',
  timings: {
    start: 1653443331616,
    socket: 1653443331617,
    lookup: 1653443331617,
    connect: 1653443331617,
    secureConnect: undefined,
    upload: 1653443331618,
    response: undefined,
    end: undefined,
    error: 1653443331622,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 0,
      tcp: 0,
      tls: undefined,
      request: 1,
      firstByte: undefined,
      download: undefined,
      total: 6
    }
  }
}

**Comment by dwaan** [comment]
Can you confirm if the latest version fix this issue?
